Add support new native majors
RevenueCat/purchases-unity pull request #485
Opened 2024-08-01 11:55 UTC by tonidero

This bumps PHC to 13.0.0 which includes breaking changes in the native SDKs: 
- iOS v5: https://github.com/RevenueCat/purchases-ios/releases/tag/5.0.0
- Android v8: https://github.com/RevenueCat/purchases-android/releases/tag/8.0.0

2024-08-01 14:53 UTC, tonidero commented
Want to test this better but this should be ready for review

2024-08-01 15:17 UTC, vegaro approved these changes
Didn't see anything to call out

2024-08-01 15:33 UTC, fire-at-will requested changes
With the note that I'm _not_ at all familiar with Unity, all of the changes that you have here look good to me!

There is one function from iOS native 5.X that we should also bring in to be safe, [recordPurchase](https://github.com/RevenueCat/purchases-hybrid-common/blob/2a04578efaa6ff668c017b69f0224538c8118db4/ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift#L507). Let me know if you have any questions about the function and I'll be happy to help!

2024-08-01 15:33 UTC, fire-at-will commented on RevenueCat/Scripts/Purchases.cs
> +            .SetPurchasesAreCompletedBy(purchasesAreCompletedBy, storeKitVersion)
🤩🤩

2024-08-01 15:53 UTC, tonidero commented
Ah yes thanks for the reminder! Will add that now

2024-08-02 14:45 UTC, fire-at-will approved these changes

2024-08-02 14:47 UTC, fire-at-will commented
The migration guide for Unity should be pretty similar to the react native one, just with Unity code samples instead of RN: https://github.com/RevenueCat/react-native-purchases/blob/main/migrations/v8-MIGRATION.md

2024-08-02 15:38 UTC, tonidero commented on RevenueCat/Scripts/Purchases.cs
> +            Debug.Log("You must set a StoreKit version if you are setting PurchasesAreCompletedBy to MyApp. For Android, it doesn't matter which");
A couple things to note here, when configuring through the Editor:
- There is no breaking change even after removing the old observer mode. So if someone was setting observer mode in the editor before, there won't be any compilation issue when they migrate to the new version.
- There is also no compile-time check that makes it so you can't set "PurchasesAreCompletedBy.MyApp" without setting storeKitVersion as well.
For these 2 reasons, we're adding this runtime check which would make it so we don't configure the SDK in this situation and log this message.

2024-08-05 11:09 UTC, merged